"""empty message

Revision ID: 164fa6f96178
Revises: 660bc8e8a48e
Create Date: 2021-07-24 12:22:46.010995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164fa6f96178'
down_revision = '660bc8e8a48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gender', table_name='people')
    op.drop_index('height', table_name='people')
    op.drop_index('name', table_name='people')
    op.drop_index('name_2', table_name='people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_2', 'people', ['name'], unique=False)
    op.create_index('name', 'people', ['name'], unique=False)
    op.create_index('height', 'people', ['height'], unique=False)
    op.create_index('gender', 'people', ['gender'], unique=False)
    # ### end Alembic commands ###
