"""empty message

Revision ID: 5b0fdf7bf499
Revises: 6860a9b56b79
Create Date: 2021-07-24 11:40:36.987222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0fdf7bf499'
down_revision = '6860a9b56b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('climate', sa.String(length=80), nullable=False))
    op.add_column('planet', sa.Column('gravity', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'gravity')
    op.drop_column('planet', 'climate')
    # ### end Alembic commands ###
