"""empty message

Revision ID: 6149d456ba92
Revises: 5b0fdf7bf499
Create Date: 2021-07-24 11:51:11.254151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6149d456ba92'
down_revision = '5b0fdf7bf499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('gender', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('height', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'people', ['gender'])
    op.create_unique_constraint(None, 'people', ['height'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'height')
    op.drop_column('people', 'gender')
    # ### end Alembic commands ###
