"""empty message

Revision ID: 660bc8e8a48e
Revises: 6149d456ba92
Create Date: 2021-07-24 12:17:33.323017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '660bc8e8a48e'
down_revision = '6149d456ba92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('passengers', sa.String(length=80), nullable=False),
    sa.Column('vehicle_class', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favoritesVehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('name', table_name='vehicles')
    op.drop_index('name_2', table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('passengers', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('vehicle_class', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'vehicles', ['name'], unique=False)
    op.create_index('name', 'vehicles', ['name'], unique=False)
    op.drop_table('favoritesVehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
